version: '3.4'

services:
  minecraft:
    container_name: minecraft
    image: jmarques15/minecraft
    env_file:
      - server.env
    hostname: minecraft
    volumes:
      - minecraft:/home/LinuxGSM/serverfiles
    stop_grace_period: 1m30s

volumes:
  minecraft: